### ISSUE TITLE
Error with Pandoc 1.16.0.2

### ISSUE THREAD

**Issue by Aminta** [chdemko/pandoc-numbering#1]
Traceback (most recent call last):
  File "/usr/local/bin/pandoc-numbering", line 9, in <module>
    load_entry_point('pandoc-numbering==0.3.3', 'console_scripts', 'pandoc-numbering')()
  File "/Library/Python/2.7/site-packages/pandoc_numbering.py", line 134, in main
    toJSONFilters([numbering, referencing])
  File "/Library/Python/2.7/site-packages/pandocfilters.py", line 76, in toJSONFilters
    altered = reduce(lambda x, action: walk(x, action, format, doc[0]['unMeta']), actions, doc)
  File "/Library/Python/2.7/site-packages/pandocfilters.py", line 76, in <lambda>
    altered = reduce(lambda x, action: walk(x, action, format, doc[0]['unMeta']), actions, doc)
  File "/Library/Python/2.7/site-packages/pandocfilters.py", line 34, in walk
    array.append(walk(item, action, format, meta))
  File "/Library/Python/2.7/site-packages/pandocfilters.py", line 27, in walk
    array.append(walk(item, action, format, meta))
  File "/Library/Python/2.7/site-packages/pandocfilters.py", line 39, in walk
    obj[k] = walk(x[k], action, format, meta)
  File "/Library/Python/2.7/site-packages/pandocfilters.py", line 25, in walk
    res = action(item['t'], item['c'], format, meta)
  File "/Library/Python/2.7/site-packages/pandoc_numbering.py", line 118, in referencing
    value[1][1] = title.replace('#', information[tag]['number'])
IndexError: list assignment index out of range
pandoc: Error running filter /usr/local/bin/pandoc-numbering
Filter returned error status 1

**Comment by chdemko** [comment]
Could you please post the md input which causes the issue?

**Comment by Aminta** [comment]
Hi!

It's your example! If you write in a test.md:

Intro #

It returns error, but if you write:

Intro #named-Id

it works!

Thanks for your help!

Davide 









Inviato da iPad

**Comment by chdemko** [comment]
I've no issue here:

~~~
$ echo "intro #" > test.md
$ pandoc --filter pandoc-numbering test.md 
<p><span id="intro:1"><strong>intro 1</strong></span></p>
$
~~~

Did you update pandoc, pandocfilters and pandoc-numbering?

**Comment by Aminta** [comment]
Sorry Cristopher, I was sure I had the latest version of pandoc but it wasn't. Very sorry. Now it works. Thanks for your help!

**Comment by chdemko** [comment]
:+1:

**Comment by Aminta** [comment]
Sorry to bother you Christopher but I made a last try.

If I use a md with this text (from your example):

This is the first section
=========================

Exercise #

This is the first exercise. Have also a look at the [](#exercise:second).


This is the second section
==========================

> Theorem #
>
> Another theorem. Can be usefull in [](#exercise:1)

Unnumbered ##



It gives the error again...

Thanks,

Davide



-- 
dr. Davide Lorigliola


Via Colloredo 7/A
33037 Pasian di Prato (Udine)
mobile +39 329 - 618 618 9 <+39%20329%20-%20618%20618%209>
davide.lorigliola@icloud.com
www.360vr.it

**Comment by chdemko** [comment]
You're right. There is an issue in the code.

I have to look at that.

In your example you did not have a "second" exercise.
~~~
Exercise (This is the second exercise) #exercise:second
~~~
