### ISSUE TITLE
Section / Headers Title using pandoc-numbering

### ISSUE THREAD

**Issue by aubertc** [chdemko/pandoc-numbering#10]
As of now, I believe it is impossible to use pandoc-numbering to decide headers titles:

```
Exercise +.#
================

Exercise +.#
--------------

## Exercise +.#

## Exercise +.# ##
```

All yields header whose names are "Exercise +.#" instead of actually numbering them.
Is this limitation on purpose? How difficult would it be to overcome it?

**Comment by chdemko** [comment]
Headers are numbered by pandoc itself http://pandoc.org/MANUAL.html#options-affecting-specific-writers (`--number-sections`)

**Comment by aubertc** [comment]
Thanks, but that wasn't exactly my question.
Header numbers and exercise numbers should be two different things.

I would like
```
## Discussion

Cf. @exercise:first.

## Exercise +.#first

Bla
```

To produce something like

> 1. Discussion
>
> Cf. Exercise 1.
>
> 2. Exercise 1
>
> Bla
>

**Comment by chdemko** [comment]
Ok, I have to think about this.

**Comment by aubertc** [comment]
Ok, great!
Remember that my last example contains only 1 syntax for headers, but that this isn't the only one (cf. first post).

**Comment by chdemko** [comment]
It seems very difficult to implement it and to be honest, I'm not sure about this feature utility. But I keep this issue opened if someone proposes a pull request able to do this.

**Comment by aubertc** [comment]
Excellent!
Looking forward to version 3.1.0!

**Comment by chdemko** [comment]
Closing this issue as there is no input

**Comment by 1earch** [comment]
Hi!

I also think that this feature could be a great improvement. I would like to use it to render appendices on a report:
```
# First section

First section content

# Second section

Second section content

# Appendices {-}

## Appendix (The first appendix title) # {-}

## Appendix (The second appendix title) # {-}
```
which could render as:
> # 1. First section
>
> First section content
> 
> # 2. Second section
> 
> Second section content
>
> # Appendices
> 
> ## Appendix 1: The first appendix title
> 
> ## Appendix 2: The second appendix title

Don't you think this could be possible?

**Comment by chdemko** [comment]
I reopen the issue to allow a PR
