### ISSUE TITLE
Link from the table of content to the listing in html output

### ISSUE THREAD

**Issue by aubertc** [chdemko/pandoc-numbering#11]
Consider the following:

```
---
pandoc-numbering:
 example:
    general:
      listing-title: List of Examples
---

# Title 

Example #first
~ Example

```
If we produce the `html` output, using

    pandoc MWE.md  --filter pandoc-numbering --toc -s -o MWE.html

then we obtain:

![image](https://user-images.githubusercontent.com/16466689/40525380-b91527b8-5fad-11e8-90d3-4dc02c51b337.png)

I.e., there is no link from the table of content to the list of example. That link is present in e.g. the `pdf` output, but is somehow missing in the `html` output.

**Comment by chdemko** [comment]
I've solved this issue. It will be published in the next version. For the moment, you can force the update to the current code using.

~~~
pip install --upgrade --force git+https://github.com/chdemko/pandoc-numbering
~~~

**Comment by aubertc** [comment]
Excellent, thanks!
