### ISSUE TITLE
List of things not meshing well with table of contents

### ISSUE THREAD

**Issue by aubertc** [chdemko/pandoc-numbering#12]
Consider the following:

```
---
pandoc-numbering:
  exercise:
    general:
      listing-title: List of exercises
      listing-identifier: myident
---

# A Title

Exercise (The first exercise) #

Exercise (The second exercise) #

```

Compiled with 

```
    pandoc test.md --toc -s --filter pandoc-numbering -o test.html
```

it will produces:

![image](https://user-images.githubusercontent.com/16466689/71024052-1376df80-20d2-11ea-8a42-2a5ec8d087b9.png)

skipping the link that should be in the table of content.
The relevant `html` part is:

> <nav id="TOC" role="doc-toc">
> <ul>
> <li><a>List of exercises</a></li>
> <li><a href="#a-title">A Title</a></li>
> </ul>
> </nav>

Whereas it should be (something like)

> <nav id="TOC" role="doc-toc">
> <ul>
> <li><a href="#myident">List of exercises</a></li>
> <li><a href="#a-title">A Title</a></li>
> </ul>
> </nav>

Note BTW that, on my installation, the example does not produce

> `List of exercises {#myident .pandoc-numbering-listing .exercise .unnumbered .unlisted}`

as listed [here](https://pandoc-numbering.readthedocs.io/en/latest/list-of-things.html), but simply

> `List of exercises {.pandoc-numbering-listing .exercise .unnumbered .unlisted}`

i.e., the id is missing.

**Comment by chdemko** [comment]
I don't have this output. Could you try to use the last version (on github)

**Comment by aubertc** [comment]
cf. #14 , I'm afraid that the last version does not work properly on my installation.

**Comment by chdemko** [comment]
Fix in current code

**Comment by aubertc** [comment]
Now, in my output (pandoc 2.9.2.1, pandoc-numbering 3.2.0.0), the list of exercises is not part of the TOC anymore. I believe such lists should be parts of the toc (or, at least, there should be a trigger to add it).

That, for instance, what the [The Chicago Manual of Style Online ](https://www.chicagomanualofstyle.org/book/ed17/frontmatter/toc.html) does: 
![image](https://user-images.githubusercontent.com/16466689/77944815-9856c500-728d-11ea-901e-3355cf3e6a05.png)
