### ISSUE TITLE
can't run sample 

### ISSUE THREAD

**Issue by Sigfried** [chdemko/pandoc-numbering#16]
I don't know if this is the same as #14. I followed the advice there (with pip and pip3, just in case):

    pip install --upgrade --force --no-cache git+https://github.com/chdemko/pandoc-numbering
    pip install --force panflute==1.11.0

I got the sample markdown from: https://github.com/chdemko/pandoc-numbering/blob/develop/docs/images/pandoc-numbering-sample.md

I was getting this:

    ⇒  pandoc  -f markdown -t latex -o numbering-sample.pdf --filter pandoc-numbering pandoc-numbering-sample.md

    Error producing PDF.
    ! Undefined control sequence.
    <recently read> \ifdef

    l.47 \ifdef

I tried various combinations of parameters and also tried the .txt sample.

And I tried, from issue #1, which works fine:

    ⇒  echo "intro #" > test.md
    ⇒  pandoc --filter pandoc-numbering test.md
    <p><span id="intro:1" class="pandoc-numbering-text intro"><strong>intro 1</strong></span></p> 

Am I doing something else wrong? I think all my stuff is python3.7 from homebrew, and

    ⇒  pandoc --version
    pandoc 2.9.2.1
    Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2

Any suggestions? It looks like this package would have saved me a lot of grief --- assuming I can get it running. I've been trying to accomplish the same thing with pandoc-crossref, which isn't easy.

Thanks!

**Comment by Sigfried** [comment]
Oh, I saw I was supposed to use the .txt file (which I did at first, but then thought I should use the .md instead)

    ⇒  pandoc --filter pandoc-numbering -o junk.pdf pandoc-numbering-sample.txt
    [WARNING] pandoc-numbering: format-entry-classic is not correct for category exercise
    [WARNING] pandoc-numbering: format-entry-title is not correct for category exercise
    Error producing PDF.
    ! Undefined control sequence.
    l.52 \ifdef

**Comment by Sigfried** [comment]
Oh, I guess I can't run the very simple thing from #1 if it's going to pdf:

    ⇒  pandoc -o text.pdf --filter pandoc-numbering test.md
    Error producing PDF.
    ! Undefined control sequence.
    <recently read> \ifdef

    l.47 \ifdef

**Comment by chdemko** [comment]
Did you install texlive-latex-extra?

**Comment by Sigfried** [comment]
Sorry, I'm not sure. I'm on a mac. Somewhat recklessly, I just uninstalled mactex (with brew) and then reinstalled (from http://www.tug.org/mactex/). I downloaded the extra stuff from https://tug.org/mactex/mactextras.html, but it's not clear how to install it.

**Comment by Sigfried** [comment]
Ok, it's all working now. I didn't do anything special to install the extra stuff, but maybe the TexLive installer thing did.
