### ISSUE TITLE
question or feature request

### ISSUE THREAD

**Issue by Sigfried** [chdemko/pandoc-numbering#17]
Thanks again for the great filter!

Is it possible to have a title with a numbered item such that:

  1. it isn't surrounded by parens? and
  2. a reference can include link text with the description and number and non-linked text with the title?

I have numbered findings listed with discussion in the results section of my paper. In the introduction, I list the findings with their first sentence or so and a link to where it appears in the results. So the results could be like the following, except somehow rendering without parens in the output pdf:

    Finding (It really blew our minds that yada yada yada) #finding:very-peculiar
     ~ We never quite got over it....

And the listing in the introduction could be like:

    [**%D #.](#finding:very-peculiar) [%T](#finding:very-peculiar no-link)

and render as if the markdown were:

    [**Finding 1.**](#finding:very-peculiar) It really blew our minds that yada yada yada

**Comment by Sigfried** [comment]
Thanks so much!

On 1) It looks like it might not be too hard to customize the output formats with hard-coded custom copies of the package; or, maybe even add a feature to allow such customization through additional config parameters? I'm not going to be able to work on that right away; my paper is long past overdue, but someday...

On 2) Thanks for that. My life would be a lot easier if I was outputting to HTML, which I understand reasonably and know how to manipulate. Sadly, I'm stuck at this point with LaTeX, which I don't.

**Comment by aubertc** [comment]
For 2., can you edit the latex source code? You could remove the links "by hand", if you really need that feature…

You could des-activate all the links (or at least, make them invisible) easily, following something along the lines of <https://tex.stackexchange.com/q/319808/34551>, but those are "uniform" solutions, that would apply to all the links…

**Comment by chdemko** [comment]
It's possible to customize the output using metadata. See https://pandoc-numbering.readthedocs.io/en/latest/formatting.html#formatting.

~~~yaml
---
pandoc-numbering:
  finding:
    standard:
      format-text-title: 'Your string format here'
    latex:
      format-text-title: 'Your string format here'
~~~

**Comment by Sigfried** [comment]
Thank you!
