### ISSUE TITLE
pip vs pip3

### ISSUE THREAD

**Issue by caseywatts** [chdemko/pandoc-numbering#19]
I had trouble finding `pip` itself on my WSL Ubuntu system using `apt-get install python-pip` (couldn't find it)

but! I got it working via `pip3`:

```bash
apt-get install python3
pip3 install pandoc-numbering
```

I don't understand python very well - is this safe to do / should we add this to the README to make it clearer?

**Comment by chdemko** [comment]
pip3 is the way that uses ubuntu to name pip for python3. You can use pip3 on ubuntu.
