### ISSUE TITLE
Does it work for equation?

### ISSUE THREAD

**Issue by panlei7** [chdemko/pandoc-numbering#2]
I tried but failed, could you give some example?

**Comment by chdemko** [comment]
Could you please post your input?

**Comment by panlei7** [comment]
```
This is the first section
=========================

$$ \alpha = 1 $$ #eq:1

From [](#eq:1)

$$
\begin{equation}
    \alpha = 1
\end{equation}
$$ #eq:2

from [](#eq:2)

$$
\begin{eqnarray}
    \alpha = 1 \\
    \beta = 2
\end{eqnarray}
$$ #eq:3
```

It seems very different from pandoc-eqnos.

**Comment by chdemko** [comment]
It has been designed to number paragraph with a heading. i.e.

~~~
Equation #
~~~

`Equation` is used as a key to determine the numbering. In your case, you cannot use `pandoc-numbering` since you don't have such heading. You have to use https://github.com/tomduck/pandoc-eqnos
