### ISSUE TITLE
Error running filter pandoc-numbering: Filter returned error status 1

### ISSUE THREAD

**Issue by salemsoprano** [chdemko/pandoc-numbering#20]
Hi,
I can't make pandoc-numbering working. Pc is on Windows 10 x64.
Pandoc 2.10.1
python 3.8.5
[pandoc-numbering_issue.txt](https://github.com/chdemko/pandoc-numbering/files/5098930/pandoc-numbering_issue.txt)
many thanks!
![pandoc-numbering_issue_PATH](https://user-images.githubusercontent.com/60630115/90683910-4d861b80-e235-11ea-988a-e3b10ff2f8d2.png)

**Comment by chdemko** [comment]
See https://github.com/sergiocorreia/panflute/issues/142

**Comment by salemsoprano** [comment]
downgraded to 2.9, everything works well! Thanks!
