### ISSUE TITLE
Gives error in Kubuntu 14.04 

### ISSUE THREAD

**Issue by ouboub** [chdemko/pandoc-numbering#3]
Hi 

I installed your filter (thanks for it) via
sudo pip install pandoc-numbering

then i run 
pandoc -t epub3 --filter pandoc-numbering theorem.md -o theorem.epub 
with the following theorem.md
Exercise (This is the first exercise) #

Exercise (This is the second exercise) #

I obtained the following error:
``
Traceback (most recent call last):
  File "/usr/local/bin/pandoc-numbering", line 11, in <module>
    load_entry_point('pandoc-numbering==2.0.2', 'console_scripts', 'pandoc-numbering')()
  File "/usr/local/lib/python2.7/dist-packages/pandoc_numbering.py", line 661, in main
    toJSONFilters([numbering, referencing])
  File "/usr/local/lib/python2.7/dist-packages/pandoc_numbering.py", line 54, in toJSONFilters
    sys.stdout.write(applyJSONFilters(actions, source, format))
  File "/usr/local/lib/python2.7/dist-packages/pandoc_numbering.py", line 89, in applyJSONFilters
    elif meta[0]:  # old API
KeyError: 0
pandoc: Error running filter pandoc-numbering
Filter returned error status 1

**Comment by chdemko** [comment]
What is your pandoc version?

~~~
pandoc -v
~~~

**Comment by ouboub** [comment]
pandoc -v
pandoc 1.17.2

**Comment by chdemko** [comment]
There was a change in pandoc 1.18 https://github.com/jgm/pandoc/releases/tag/1.18 concerning meta internal format. Could you please update your pandoc version.
See http://pandoc.org/installing.html#linux

**Comment by ouboub** [comment]
Hi, 
I did this (after some trouble) and i used 
/home/oub/.local/bin/pandoc --version
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
Default user data directory: /home/oub/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

but i obtain the same error, sorry

the version says 1.19.2 but compiled with pandoc 1.17 I am confused

**Comment by chdemko** [comment]
No input on this issue, closing it
