### ISSUE TITLE
Conflict with pandoc-citeproc regarding the @notation

### ISSUE THREAD

**Issue by aubertc** [chdemko/pandoc-numbering#6]
[pandoc-citeproc](https://github.com/jgm/pandoc-citeproc) is a commonly used filter for pandoc, that also use the `@` symbol.

Using both pandoc-citeproc and pandoc-numbering in the same document results in the impossibility to use the `@` notation from pandoc-numbering:

```
Exercise #exercise:second

Have a look at @exercise:second 
```
compiled with

`pandoc MWE.md --filter pandoc-citeproc --filter pandoc-numbering -o MWE.pdf`

results in 

`pandoc-citeproc: reference exercise:second not found`

Is there any way to use have an option allowing to use a different symbol in `pandoc-citeproc` for the [shortcut notation](https://github.com/chdemko/pandoc-numbering/wiki#use-of-cite-shortcut-notation)?

**Comment by chdemko** [comment]
The filter order is important:

try

~~~
pandoc MWE.md --filter pandoc-numbering --filter pandoc-citeproc -o MWE.pdf
~~~

**Comment by chdemko** [comment]
In general, filter order is important. But you can add a paragraph in the wiki https://github.com/chdemko/pandoc-numbering/wiki
