### ISSUE TITLE
Inline Vs Block environments

### ISSUE THREAD

**Issue by aubertc** [chdemko/pandoc-numbering#7]
There are a couple of usages in the [example file](https://raw.githubusercontent.com/wiki/chdemko/pandoc-numbering/images/pandoc-numbering-sample.txt) that are left unspecified:

- Why are the theorems enclosed in quotation environments?
- What is the benefit of writing 

```
Example -.#
 ~ This is the second example of the second section
```

over

```
Example -.#

This is the second example of the second section
```
? Why is the former rendered in latex as enclosed in `description` environments?

I guess this is connected to having e.g. exercises that spans over multiple lines, but are still enclosed within the same "environment", but can't exactly tell what your usage is.

**Comment by chdemko** [comment]
* Why are the theorems enclosed in quotation environments?

It's just the sample, no interest for numbering

* What is the benefit of writing...

It was a pull request to add support for definition lists https://github.com/chdemko/pandoc-numbering/pull/5

The former numbers a definition list (http://pandoc.org/MANUAL.html#definition-lists) and the latter numbers a paragraph
